 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/intakes", type: :request do
  # Intake. As you add validations to Intake, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Intake.create! valid_attributes
      get intakes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      intake = Intake.create! valid_attributes
      get intake_url(intake)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_intake_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      intake = Intake.create! valid_attributes
      get edit_intake_url(intake)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Intake" do
        expect {
          post intakes_url, params: { intake: valid_attributes }
        }.to change(Intake, :count).by(1)
      end

      it "redirects to the created intake" do
        post intakes_url, params: { intake: valid_attributes }
        expect(response).to redirect_to(intake_url(Intake.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Intake" do
        expect {
          post intakes_url, params: { intake: invalid_attributes }
        }.to change(Intake, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post intakes_url, params: { intake: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested intake" do
        intake = Intake.create! valid_attributes
        patch intake_url(intake), params: { intake: new_attributes }
        intake.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the intake" do
        intake = Intake.create! valid_attributes
        patch intake_url(intake), params: { intake: new_attributes }
        intake.reload
        expect(response).to redirect_to(intake_url(intake))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        intake = Intake.create! valid_attributes
        patch intake_url(intake), params: { intake: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested intake" do
      intake = Intake.create! valid_attributes
      expect {
        delete intake_url(intake)
      }.to change(Intake, :count).by(-1)
    end

    it "redirects to the intakes list" do
      intake = Intake.create! valid_attributes
      delete intake_url(intake)
      expect(response).to redirect_to(intakes_url)
    end
  end
end
