 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/outtakes", type: :request do
  # Outtake. As you add validations to Outtake, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Outtake.create! valid_attributes
      get outtakes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      outtake = Outtake.create! valid_attributes
      get outtake_url(outtake)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_outtake_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      outtake = Outtake.create! valid_attributes
      get edit_outtake_url(outtake)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Outtake" do
        expect {
          post outtakes_url, params: { outtake: valid_attributes }
        }.to change(Outtake, :count).by(1)
      end

      it "redirects to the created outtake" do
        post outtakes_url, params: { outtake: valid_attributes }
        expect(response).to redirect_to(outtake_url(Outtake.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Outtake" do
        expect {
          post outtakes_url, params: { outtake: invalid_attributes }
        }.to change(Outtake, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post outtakes_url, params: { outtake: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested outtake" do
        outtake = Outtake.create! valid_attributes
        patch outtake_url(outtake), params: { outtake: new_attributes }
        outtake.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the outtake" do
        outtake = Outtake.create! valid_attributes
        patch outtake_url(outtake), params: { outtake: new_attributes }
        outtake.reload
        expect(response).to redirect_to(outtake_url(outtake))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        outtake = Outtake.create! valid_attributes
        patch outtake_url(outtake), params: { outtake: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested outtake" do
      outtake = Outtake.create! valid_attributes
      expect {
        delete outtake_url(outtake)
      }.to change(Outtake, :count).by(-1)
    end

    it "redirects to the outtakes list" do
      outtake = Outtake.create! valid_attributes
      delete outtake_url(outtake)
      expect(response).to redirect_to(outtakes_url)
    end
  end
end
